---

# common
- hosts: all
  become: yes
  gather_facts: no

  roles:
    - common

# webserver
- hosts: web
  become: yes

  roles:
    - webserver


# loadbalancer
- hosts: lb
  become: yes

  roles:
    - loadbalancer

# monitor
- hosts: monitor
  become: yes

  roles:
    - monitor


