---
- name: Install nginx latest on the server
  apt: name=nginx state=latest

- name: Copy nginx configuration file
  copy:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Write default nginx
  copy:
    src: templates/default-site.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: Copy and deploy website content
  copy:
    src: files/explorecalifornia/
    dest: /usr/share/nginx/html/
